# Generated by Django 4.2.5 on 2023-09-22 04:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model",
                    models.CharField(max_length=20, verbose_name="Kompyuter modeli"),
                ),
                (
                    "processor",
                    models.CharField(
                        max_length=20, verbose_name="Kompyuter protsessori"
                    ),
                ),
                (
                    "graphic_card",
                    models.CharField(
                        max_length=30, verbose_name="Kompyuter videokartasi"
                    ),
                ),
                ("ram", models.SmallIntegerField(verbose_name="Operativ xotira")),
                ("rom", models.SmallIntegerField(verbose_name="Doimiy xotira")),
                (
                    "display_diagnal",
                    models.DecimalField(
                        decimal_places=1, max_digits=3, verbose_name="Ekran diagnali"
                    ),
                ),
                ("used", models.BooleanField(default="False", verbose_name="Yangi")),
                (
                    "os",
                    models.SmallIntegerField(
                        choices=[
                            ("1", "Windows"),
                            ("2", "Linux"),
                            ("3", "MacOs"),
                            ("4", "MsDOC"),
                        ],
                        verbose_name="Operatsion tizim",
                    ),
                ),
            ],
        ),
    ]
